name: opencl-cts
base: core24
confinement: classic
platforms:
  amd64:
    build-on: [amd64]
  arm64:
    build-on: [amd64, arm64]
version: '1.0'
summary: Khronos OpenCL Conformance Test Suite
description: |
  Baseline snap for the Khronos OpenCL CTS. Builds the test_conformance
  tests from source via CMake and ships an executable for running tests.

apps:
  test:
    command: test
    plugs:
      - opengl            # GPU access on many platforms
      - hardware-observe  # Inspect devices
      - home              # Read/write logs
      - network           # Optional: some runners fetch data/plugins
    environment:
      LD_LIBRARY_PATH: "/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH"
  list-tests:
    command: list_tests

parts:
  test-conformance:
    source: bin/
    plugin: dump
    stage:
      - test

  list-tests:
    source: bin/
    plugin: dump
    stage:
      - list_tests

  opencl-cts:
    plugin: nil
    source: https://github.com/KhronosGroup/OpenCL-CTS.git
    source-branch: v2024-02-27-00
    source-type: git
    after:
      - test-conformance
      - list-tests
    build-packages:
      - build-essential
      - cmake
      - git
      - pkg-config
      - python3
      - python3-yaml
      - opencl-headers
      - ocl-icd-opencl-dev
      - spirv-headers
    stage-packages:
      -  ocl-icd-libopencl1
    override-build: |
      set -eux
      cmake -S "$SNAPCRAFT_PART_SRC" -DCL_INCLUDE_DIR=/usr/include/CL -DCL_LIB_DIR=/usr/lib/  -DOPENCL_LIBRARIES=OpenCL
      cmake --build . --config Release
      
      craftctl default
      mkdir "${CRAFT_PART_INSTALL}/usr/bin"
      cp "${CRAFT_PROJECT_DIR}/bin/test" "${CRAFT_PART_INSTALL}/usr/bin/test"
      cp "${CRAFT_PROJECT_DIR}/bin/list_tests" "${CRAFT_PART_INSTALL}/usr/bin/list_tests"

      mkdir -p "${CRAFT_PART_INSTALL}/usr/bin/"
      cp -r "${SNAPCRAFT_PART_BUILD}/test_conformance" "${CRAFT_PART_INSTALL}/usr/bin/"
